#!/bin/bash

WORKSPACE="$1"
IMAGE_NAME="$2"
LAST_SUCCESSFUL_BUILD="$3"
BUILD_NUMBER="$4"

SCRIPTS_SRC_PATH="${WORKSPACE}/target/api/docker*.sh"
SCRIPTS_DESTINATION_FOLDER="/home/ec2-user/scripts"
PERM_KEY="/Users/abninder/aws_credentials/docker-app.pem"
EC2_INSTANCE="ec2-user@ec2-35-171-176-196.compute-1.amazonaws.com"
DOCKER_CONTAINER_STARTUP_CMD="sudo docker run -p 8082:8085 -e LISTEN_PORT=8085 ${IMAGE_NAME}:${BUILD_NUMBER}"

scp -i ${PERM_KEY} ${SCRIPTS_SRC_PATH} ${EC2_INSTANCE}:${SCRIPTS_DESTINATION_FOLDER}
sh -i ${PERM_KEY} ${EC2_INSTANCE} ${SCRIPTS_DESTINATION_FOLDER}/docker-stop.sh ${IMAGE_NAME}:${LAST_SUCCESSFUL_BUILD}
ssh -i ${PERM_KEY} ${EC2_INSTANCE} ${SCRIPTS_DESTINATION_FOLDER}/docker-fetch-image.sh ${IMAGE_NAME}:${BUILD_NUMBER}
ssh -i ${PERM_KEY} ${EC2_INSTANCE} ${DOCKER_CONTAINER_STARTUP_CMD}